name: Banking API CI pipeline

on:
 push:
  branches:
    - main


jobs:
  build-and-test:
   runs-on: ubuntu-latest

   steps: 

   - name: checkout code
     uses: actions/checkout@v4

   - name: Java stepup
     uses: actions/setup-java@v4
     with:
        distribution: temurin
        java-version: '17'

   - name: Sonarqube scan
     run: echo sonarsource/sonarqube-scan@v5

  container-validation:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:

    - name: checkout code
      uses: actions/checkout@v4

    - name: Java stepup
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'

    - name: Docker build
      run: docker build -t banking-api:1.0 .

    - name: Trivy scan
      uses: aquasecurity/trivy-action@master
      with: 
        image-ref: 'banking-api:1.0'
        severity: HIGH,CRITICAL

  Infrastructure-validation:
    needs: container-validation
    runs-on: ubuntu-latest
    
    steps:

      - name: chekout code
        uses: actions/checkout@v4

      - name: Java installation
        uses: actions/setup-java@v5
        with:
            distribution: temurin
            java-version: '17'

      - name: Terraform Installation
        uses: hashicorp/setup-terraform@v3
        with: 
            terraform_version: 1.12.2

          



