name: Banking API CI pipeline

on:
 push:
  branches:
    - main


jobs:
  build-and-test:
   runs-on: ubuntu-latest

   steps: 

   - name: checkout code
     uses: actions/checkout@v4

   - name: Java stepup
     uses: actions/setup-java@v4
     with:
        distribution: temurin
        java-version: '17'

   - name: Sonarqube scan
     run: echo sonarsource/sonarqube-scan@v5

   - name: Print Current Directory
     run: pwd

   - name: List Files
     run: ls -la

   - name: Print Workspace
     run: echo $GITHUB_WORKSPACE

   - name: print Welcome Aditya
     run: echo "Welcome to GitHub Actions World"